pages/kit-docs/overview.mdx
Removing a type import from the JS example for drizzle-kit config, since you cannot import types this way in JS (and it's also unused anyways)
=> Fix type import in JS configuration

pages/docs/column-types/pg.mdx, pages/docs/installation-and-db-connection/postgresql/postgresjs.mdx
Fix for some errors on postgres docs
- Fix typo wrong variable name for client on example (postgresjs.mdx)
- Fix typo sqliteTable import should be pgTable (column-types/pg.mdx)
- Fix missing uuid import from drizzle-orm/pg-core (column-types/pg.mdx)
=> Fix typo in postgresjs.mdx

pages/kit-docs/conf.mdx
The docs currently suggest to put sensitive data into source control which is usually not desired.
=> Use environment variables for sensitive data in drizzle kit config docs

pages/docs/sql-schema-declaration.mdx
The docs mentioned 
```ts
import { InferModel } from 'drizzle-core/pg-core';
```
which was incorrect. 
It has been corrected to
```ts
import { InferModel } from 'drizzle-core';
```
=> Corrected import path of 'InferModel' in the schema declaration page

pages/kit-docs/conf.mdx
PlanetScale gives you connection strings with `?sslaccept=strict`, which doesn't work, whereas `?ssl={"rejectUnauthorized":true}` does work.
Seen this pop up a few times so figured it was worth adding now that push is out of preview.
=> Add note about PlanetScale SSL connection strings

pages/docs/installation-and-db-connection/mysql/mysql2.mdx
FIXED:
- Removed "are" from mysql2 documentation page to fix grammar error
=> Grammar error in documentation: MySQL2 database connection

pages/docs/column-types/mysql.mdx
Fixed wrong import in [here](https://orm.drizzle.team/docs/column-types/mysql)
=> Fix mysql import from `varchar` to `text`

pages/docs/crud.mdx
Fix users table name in partial query syntax example.
=> docs: fix users table name in partial query syntax

pages/docs/installation-and-db-connection/postgresql/vercel.mdx
Updated the link to @vercel/postgress. Old link was linking to the https://github.com/neondatabase/serverless.
=> docs: fix vercel/postgress links at vercel.mdx

pages/docs/operators.mdx
As far as I'm aware ilike is a postgres exclusive so it should not be marked as supported in the docs for mysql and sqlite.
Related discord thread - https://discord.com/channels/1043890932593987624/1096009424092528650
=> Mark ilike as not supported for mysql and sqlite

pages/docs/rqb.mdx
Table defined as `groups` so should be `groups` instead of `groupsTable`
=> Fix typo in many-to-many example

pages/docs/installation-and-db-connection/mysql/mysql2.mdx
Found a code example typo in ```mysql``` connection doc page
(```connection``` changed to ```poolConnection```)
=> Code example typo fix in mysql connection page

pages/docs/rqb.mdx
Found the `many` parameter is not actually used in the example.
=> docs: remove extra parameter destructuring in one-to-one usersRelations example

pages/kit-docs/conf.mdx
Typo error in Drizzle Kit Configuration doc
=> typo : fix typo on  conf.mdx

pages/docs/rqb.mdx
I tried to run the example locally but there is an issue with a query, take a look at screenshots to get it:
currently in the docs:
with the fix:
=> docs: fix many to many example

components/Icons/Icons.tsx, components/IsSupportedChip/IsSupportedChip.module.css, components/IsSupportedChip/IsSupportedChip.tsx, components/IsSupportedChip/IsSupportedChipGroup.tsx, pages/docs/crud.mdx, pages/docs/operators.mdx, pages/docs/schemas.mdx, pages/docs/views.mdx
This is an implementation of option 2 from this issue: https://github.com/drizzle-team/drizzle-orm/issues/864
It changes the "database support UI" from this:
To this:
The additional spacing is just a consequence of how the MDX files get rendered with the injected component instead of the previous backticks UI. If necessary, I can try to reverse-engineer the rendering and remove the spacing, but it looks ok in context, IMHO. 
Also, I implemented option 3 as an alternative if you decide to go that route, and commented out the CSS:
```css
.is-supported-yes {
/* Uncomment for higher visual hierarchy style */
/* border: none;
background: #273D2E; */
color: #47B66D;
}
.is-supported-no {
/* Uncomment for higher visual hierarchy style */
/* border: none;
background: #3A2828; */
color: #f36464;
} …
```
=> Improve supported databases UI (implement IsSupportedChip, IsSupportedChipGroup components

pages/docs/rqb.mdx
Fixed typo where the "users" table was referenced as "user". This change resolves #52.
=> Docs: Fixed typo in Relational queries page.

pages/docs/sql-schema-declaration.mdx
Fixed a small error in the docs, the `InferModel` should be imported from `'drizzle-orm'`, not `'drizzle-orm/sqlite-core'`. Thanks for the awesome work on this project! :smile:  I've been enjoying working with it a lot on a side project of mine lately.
=> fix(sqlite): update InferModel import location for SQLite example

pages/docs/sql-schema-declaration.mdx
getting error from the return type in schema declaration example, which should be array of users
=> fix: SQL-schema-declaration-type-error

pages/docs/column-types/pg.mdx
The purpose of this pull request is to improve the clarity of the enum example. I encountered some difficulties in understanding that I needed to export the custom enum in the schema file in order to generate the SQL code for creating the enum in Postgres. This change aims to provide better documentation and guidance for others who may encounter the same issue.
=> fix(docs): update pg.mdx

theme.config.tsx
Fixes the homepage embed typo
Please take your time to thoroughly review this 1 character addition
=> Fix typo in meta description

pages/kit-docs/config-reference.mdx
As I was trying to make studio work for my local setup, I blindly followed the instructions and just added `url: ""` to the config. 
Then, obviously, I ran into some errors.
I then googled and ran into the following article and saw the `url` could also be used as "path for the local file".
In hindsight it's obvious, while trying to make it work, it wasn't
So I thought to add this to save the time for others
=> docs: add comment for sqlite url config

pages/kit-docs/config-reference.mdx
Fix small typo in configuration reference page of Drizzle kit, "casing" section
=> fix typo in configuration reference page

pages/docs/column-types/pg.mdx, pages/docs/indexes-constraints.mdx
On PostgreSQL examples a `get_random_uuid()` is used, this function does not exists and should be changed to `gen_random_uuid()`
=> fix: postgres uuid declaration

pages/kit-docs/commands.mdx
Launch is spelled incorrectly on https://orm.drizzle.team/kit-docs/commands#drizzle-studio-new
=> tiny typo in Drizzle Studio 

pages/docs/goodies.mdx
Without the `typeof` operator, TypeScript will give this error "Cannot find namespace"
Kinda of an obvious typo but I spent way too much time debugging this, hoping to prevent others from falling into the same trap.
=> fix(goodies): incorrect use of `$infer` helpers

pages/docs/overview.mdx
Corrects a minor typo in the documentation overview, changing "PostrgeSQL" to "PostgreSQL" Reviewed the codebase to ensure the change is consistent with the other spellings of PostgreSQL.
=> Fix Typo in Documentation Overview (PostrgeSQL => PostgreSQL)

pages/docs/sql.mdx
The current example for fulltext search leads to an error that is tracked in this issue.
https://github.com/drizzle-team/drizzle-orm/issues/1140
This change should remediate that.
=> fix: typo in fulltext search example

pages/docs/perf-queries.mdx
Replaced deprecated "placeholder" import with "sql.placeholder" as described here: https://github.com/drizzle-team/drizzle-orm/blob/a7dc7e8bbdc3784f67ff32ce39bee3283f080751/drizzle-orm/src/sql/index.ts#L564
=> Updated "Query performance" docs

pages/docs/quick-sqlite/d1.mdx
Since [wrangler 3.0](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.0.0), the `wrangler dev` `--local` flag was **deprecated**, and running locally became the default behavior. The `--persist` flag was **removed**, and persisting data from D1 also became the default behavior.
This pull request removes mentions to those flags from commands, and adds a reminder for users of older versions, since this was a fairly recent change.
=> Remove deprecated and removed wrangler flags from D1 docs

theme.config.tsx
```html
<meta name="description" content="Drizzle ORM | %s">
```
```html
<meta name="description" content="Drizzle ORM is a lightweight and performant TypeScript ORM with developer experience in mind">
```
=> fix: %s in descriptions

src/content/documentation/docs/goodies.mdx
This is not async function.
See code for references:
- [MySQL](https://github.com/drizzle-team/drizzle-orm/blob/d20bd54cfbc7a8ead2b14eb24af7b73c752b80e2/drizzle-orm/src/mysql-core/utils.ts#L17)
- [PostgreSQL](https://github.com/drizzle-team/drizzle-orm/blob/d20bd54cfbc7a8ead2b14eb24af7b73c752b80e2/drizzle-orm/src/pg-core/utils.ts#L14)
- [SQLite](https://github.com/drizzle-team/drizzle-orm/blob/d20bd54cfbc7a8ead2b14eb24af7b73c752b80e2/drizzle-orm/src/sqlite-core/utils.ts#L17)
=> Remove `await` from `getTableConfig(table)`

src/content/documentation/docs/get-started-postgresql.mdx
- Updates the WebSockets example so that it's similar to the HTTP example
- Removes the experimental `neonConfig.fetchConnectionCache = true;` feature from the HTTP example. We aim to enable this by default in the future.
- Add info about when to use HTTP vs WebSockets
- Additional links to Neon docs + minor revisions
=> Update Neon serverless driver instructions

src/components/layout/LogoDocs.astro
I (and other people probably) like to do `cmd` `1`, `cmd` `2`, `cmd` `3`, etc to go to my first/second/third browser tab, but right now the `1`, `2`,  and `3` shortcuts on the docs are preventing those browser shortcuts. This PR should fix that by adding the condition `!e.metaKey`.
=> fix: prevent overriding browser shortcuts (cmd 1, cmd 2, cmd 3)

src/content/tutorials/drizzle-on-the-edge/drizzle-with-vercel-edge-functions.mdx
This corrects the statement that Neon's serverless driver is compatible with any Postgres provider. The serverless driver is only compatible with environments where Neon's HTTP/WebSocket proxy is deployed in front of Postgres.
=> fix: apply corrections to edge docs for vercel/neon

src/content/tutorials/drizzle-with-frameworks/drizzle-nextjs-neon.mdx
In the docs, there is an piece of code that shows the following:
```js
export const addTodo = async (id: number, text: string) => {
await db.insert(todo).values({
id: id,
text: text,
});
};
```
But at in the end, in the topic: "Establish server-side functions", it was wrong, because the functions didn't provided the function param to pass the id, causing a type error in typescript.
The code now fix that error.
=> fix: missing id param in function example in code example

src/content/documentation/docs/column-types/pg.mdx
In the example on the `varchar` column type for Postgres, you are defining two columns with the same name. This change fixes the naming to not be duplicated.
=> Fix typo in column type docs

src/content/documentation/docs/joins.mdx
There is unnecessary '2' written at the end of tables name in examples for one to many joins.
=> docs: Remove erroneous '2' in join statement example

src/content/documentation/docs/update.mdx
I couldn't remember offhand today whether passing `undefined` within an update object would do nothing, set the column to null, or create some error. Confirmed the behavior with the code but wanted to update the docs for future people who wonder.
=> Add more detail to what the keys and values of the update object can be

src/content/documentation/docs/rqb.mdx
Fixes https://github.com/drizzle-team/drizzle-orm-docs/issues/335
Would be nice if the following elements are documented as well:
- `one` relations must be defined on both tables.
- `fields` and `references` should be defined on one side.
- `fields` and `references` changes if the queried result is nullable:
```ts
const profileInfo = await queryProfileInfoWithUser();
//____^? type { id: number, user: { ... }  }
```
=> docs: add relation in one-to-one example

src/content/documentation/docs/joins.mdx
`joins.mdx` reference an `alias` function which isn't exported from `drizzle-orm`, replace with `aliasedTable` instead.
=> Correct alias reference to aliasedTable

src/content/documentation/docs/transactions.mdx
The type signature for `tx.rollback()` is `(void) => never` because the expected behavior is that calling this method throws an error that causes the driver to rollback the transaction.
The example as is currently written contradicts this expectation. The `await` in the example implies that `tx.rollback()` returns a promise that must be awaited. Not only does TypeScript flag this as an issue 
```
typescript: 'await' has no effect on the type of this expression
```
but in correctly using rollback in a non-async function would cause an application to crash e.g. uncaught promise error.
This update removes the await keyword and adds a comment indicating the expected behavior.
=> fix: Incorrect documentation for usage of tx.rollback()

src/content/documentation/docs/joins.mdx
This PR fixes the self-join example in the documentation.
- Corrected the self-join example to use `user.parentId` instead of `user.id` for the join condition.
=> Fix self-join example in documentation

src/content/documentation/kit-docs/upgrade-21.mdx
A little fix on the "upgrading to `v0.21.0`" file because are missing a comma on the config object example.
=> fix: missing comma on upgrade

src/content/documentation/docs/get-started-sqlite.mdx
Related to https://github.com/drizzle-team/drizzle-orm/pull/2357
```
Update the D1 example to use Wrangler's D1 migrations API instead of executing individual commands for each file.
```
=> docs: Updated Cloudflare D1 example to use wrangler's migrations API

src/content/documentation/docs/joins.mdx
Hello ! As I was reading examples about joins [in here](https://orm.drizzle.team/docs/joins#joins-sql), I found an inconsistent type declaration and thought I would go ahead and propose a fix :) Thank you for all your hard work. 
-----
<a href="https://stackblitz.com/~/github.com/epaumier/drizzle-orm-docs/tree/epaumier/patch-65137"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/epaumier/drizzle-orm-docs/tree/epaumier/patch-65137)._
=> fix: incorrect type declaration

src/content/documentation/docs/migrations.mdx
`migrate` method is not exposed as a part of`drizzle-orm/node-postgres`
ref - https://github.com/drizzle-team/drizzle-orm/blob/526996bd2ea20d5b1a0d65e743b47e23329d441c/drizzle-orm/src/node-postgres/index.ts
=> Fixed migrations docs for Option 4 migration scenario

src/content/documentation/docs/migrations.mdx
=> typo fix in migrations.mdx, scheama -> schema

src/content/documentation/docs/get-started/expo-new.mdx
Fixing typos, should be babel.config.js instead of metro.config.js
=> docs(Expo SQLite): fix js copy filename

src/content/documentation/docs/tutorials/drizzle-with-db/drizzle-with-turso.mdx
I was getting errors with the existing code snippet.
The first error was a zod validation because `turso` is not a valid driver.
After removing the driver config line, I was getting a type error with sqlite as the dialect because it expects the token config to be a `token` prop instead of `authToken`.
After digging into the source code and identifying the `Dialect` type, it seems that the proper value for dialect is `turso`.
=> fix: update dialect for turso tutorial

src/content/docs/typebox.mdx, src/content/docs/valibot.mdx, src/content/docs/zod.mdx
This PR overhauls the documentaiton for drizzle-zod, drizzle-valibot and drizzle-typebox packages to include more specific details on use, examples and references.
=> Update docs for validator libraries

src/content/docs/extensions/pg.mdx, src/content/docs/generated-columns.mdx, src/content/docs/guides/cursor-based-pagination.mdx, src/content/docs/guides/postgis-geometry-point.mdx, src/content/docs/guides/postgresql-full-text-search.mdx, src/content/docs/guides/unique-case-insensitive-email.mdx, src/content/docs/guides/vector-similarity-search.mdx, src/content/docs/indexes-constraints.mdx, src/content/docs/migrate/migrate-from-prisma.mdx, src/content/docs/migrate/migrate-from-sequelize.mdx, src/content/docs/migrate/migrate-from-typeorm.mdx, src/content/docs/relations.mdx, src/content/docs/rqb.mdx, src/content/docs/sql-schema-declaration.mdx, src/mdx/get-started/mysql/IntrospectMySQL.mdx, src/mdx/get-started/mysql/UpdateSchema.mdx, src/mdx/get-started/postgresql/IntrospectPostgreSQL.mdx, src/mdx/get-started/postgresql/UpdateSchema.mdx, src/mdx/get-started/singlestore/IntrospectSingleStore.mdx, src/mdx/get-started/singlestore/UpdateSchema.mdx, src/mdx/get-started/sqlite/IntrospectSqlite.mdx, src/mdx/get-started/sqlite/UpdateSchema.mdx
There has been a decent amount of confusion surrounding the deprecation of the third param of tables when being defined as objects, mainly due to the documentation not being up to date with that. This PR fixes that.
=> Remove instances of deprecated third param in table definition

src/content/docs/connect-cloudflare-do.mdx, src/content/docs/get-started/do-new.mdx
[Durable Objects](https://developers.cloudflare.com/durable-objects/api/sql-storage/) have VERY fast access to a local SQLite database.
The idiomatic way of using them is to bundle all the database accesses within a function inside the Durable Object class and call that function from the Worker code, otherwise every interaction with the database would lead to a round-trip from the Worker location to the Durable Object instance location.
Disclosure: I didn't actually deploy this code on Workers. I assume what was there already is actually runnable, and I only moved some calls around.
=> Fix Durable Objects example to be idiomatic

src/mdx/LibsqlTable.mdx
changed \`platofrm\` to \`platform\`
=> fix: typo in LibsqlTable.mdx

src/content/docs/drizzle-kit-generate.mdx
`drizzle-kit push` was used to show example.
=> fix: typo in drizzle-kit-generate.mdx

src/content/docs/generated-columns.mdx
Fixed a small typo. "do you" -> "for you."
=> fix: typo in generated-columns.mdx

src/content/docs/drizzle-kit-generate.mdx
Small fix to `generate` command examples that were referencing `push` command instead.
=> docs: fix generate docs typo

src/content/docs/connect-cloudflare-d1.mdx
Since wrangler now supports both `wrangler.json` and `wrangler.toml` I've updated the Cloudflare D1's docs page to provide an example with `wrangler.json` too.
=> docs: Updated Cloudflare D1 example to include wrangler.json

src/content/docs/batch-api.mdx
New doc link is https://developers.cloudflare.com/d1/worker-api/d1-database/#batch instead of https://developers.cloudflare.com/d1/platform/client-api/#batch-statements
=> Update link to d1 batch API

src/mdx/LibsqlTable.mdx
changed `conneciton` to `connection`
=> Fix typo in LibsqlTable.mdx

src/content/docs/drizzle-kit-pull.mdx
Fixed error: Unrecognized options for command 'introspect': --schema
=> Updated drizzle-kit-pull.mdx: Fixed error caused by CLI arguments

src/content/docs/connect-overview.mdx
This commit removes extra whitespace in the import statements for `drizzle-orm/planetscale` and `drizzle-org/d1` in the Database connection page on the documentation website (https://orm.drizzle.team/docs/connect-overview).
=> Remove extra whitespace character from imports

src/content/docs/drizzle-config-file.mdx
- Remove `extensionsFilters: ` from the start of the line in the entities example code block.
=> fix(docs) fix typo in example in drizzle-config-file.mdx

src/content/docs/drizzle-config-file.mdx, src/mdx/DriversExamples.mdx
This PR fixes minor syntax issues in the MDX documentation file, including missing closing brackets and semicolons.
=> Fix missing closing brackets and semicolons in docs

src/content/docs/get-started-gel.mdx
I think this may have been inadvertently kept when copying and pasting the Postgres page?
=> Fix Drizzle <> Gel title

src/content/docs/prisma.mdx
=> Fix typo in prisma limitations

src/content/docs/data-querying.mdx
This PR fixes the typo I stumbled upon while browsing the documentation.
=> fix: typo in query data section

src/content/docs/migrations.mdx
The schema demo code in [Option 2](https://orm.drizzle.team/docs/migrations#how-can-drizzle-help) misses the right bracket
=> docs: Update migrations.mdx

src/content/docs/cache.mdx
`CacheConfig.ex` is documented to be in seconds while the example implementation directly used it as an argument in the `put` method from Keyv (which accepts ttl in milliseconds)
https://github.com/jaredwray/keyv/tree/main/packages/keyv#setkey-value-ttl
=> Fix the Keyv cache example to have correct TTL

src/content/docs/sql-schema-declaration.mdx
The text for a single schema file appeared again in the section for multiple schema files. I assume it was a copy & paste error
=> Remove duplicate text

src/content/docs/rqb.mdx
The schema is missing the field `verified` even tho later in the docs says at: https://orm.drizzle.team/docs/rqb#find-many
```
// result type
const result: {
id: number;
name: string;
verified: boolean;
invitedBy: number | null;
}[];
```
=> [docs] add missing field in the schema

src/content/docs/drizzle-config-file.mdx
Fix protocol of `dbCredentials.url` in drizzle-config-file page.
For dialect `"mysql"`, the protocol should be `mysql://` instead of `postgres://`.
| Before | After |
| ------ | ----- |
| ![image](https://github.com/user-attachments/assets/1c9df03b-35a9-488a-a8f1-9b02c6bd4e8e) | ![image](https://github.com/user-attachments/assets/8ba88548-8bbb-411c-94ff-dbe53dc006a0) |
=> docs: fix typo in `dbCredentials.url` to use correct protocol for MySQL

src/content/docs/connect-bun-sql.mdx
This removes a callout from the Drizzle/Bun page, since the referenced issue has been fixed.
=> Update documentation for Bun

src/content/docs/connect-expo-sqlite.mdx, src/content/docs/connect-op-sqlite.mdx
```ts
import type { Config } from 'drizzle-kit';
export default {
// ...
} satisfies Config;
```
```ts
import { defineConfig } from 'drizzle-kit';
export default defineConfig({
// ...
});
```
To match the content of the [drizzle.config.ts docs](https://orm.drizzle.team/docs/drizzle-config-file).
=> docs: use `defineConfig` instead of `Config`
