drizzle-team/drizzle-orm-docs

pages/docs/installation-and-db-connection/mysql/planetscale.mdx

- fix link of database-js  planetscale dependency

Fix: Link of database-js dependency

---

components/pages/LandingPage/LandingPage.tsx

Hey Drizzle team 👋 
Noticed a minor typo on your homepage, wanted to share the fix because I'm sure that one gets a lot of eyes on it!
Have a great day!

📝 Fix typo "serveless" on homepage

---

pages/docs/installation-and-db-connection/postgresql/supabase.mdx

Hi all! 
Added a quick guide for using Drizzle with Supabase.

Add Supabase guide

---

pages/docs/sql-schema-declaration.mdx

docs: Update sql-schema-declaration.mdx

---

pages/docs/views.mdx

docs: fix typo on views page

---

components/pages/LandingPage/LandingComponents/DrizzleCloud/DrizzleStudio.module.css

CHANGED:
- Added border to documentation button in dark theme

Fix | Documentation button border

---

pages/docs/sql-schema-declaration.mdx

I didn't realize that I hadn't exported users and wasted several hours before I got the migration working. ┐(´д｀)┌

Fix the forgetting to write export

---

pages/docs/installation-and-db-connection/postgresql/supabase.mdx

Addition to show a quick example of how to use Drizzle with Supabase and Cloudflare Workers

How to use supabase with cloudflare workers

---

pages/docs/_meta.json
pages/docs/batch-api.mdx
pages/docs/column-types/sqlite.mdx
pages/docs/operators.mdx

1. Add new postgres operators for array
2. Add batch api docs section
3. Add sqlite json mode for text

Add changes for 0.28.6 release

---

pages/docs/rqb.mdx

Add docs on how to disambiguate relations when using the Query API.
Following https://discord.com/channels/1043890932593987624/1160230490071121991
Let me know if there are some changes needed. Thanks!

feat: add rqb disambiguating relations section

---

src/content/documentation/docs/get-started-sqlite.mdx

Just a small typo that I have found.

fix(sqlite): fix small typo

---

src/content/documentation/docs/insert.mdx

Resolves #193 
This is currently undocumented.

docs: document upsert with composite indexes

---

src/content/documentation/docs/get-started-postgresql.mdx

This depends on https://github.com/drizzle-team/drizzle-orm/pull/1902 but I'm opening it a bit early for your review.
I tried to follow the structure of the other docs on the same page.

Add Xata to the Postgres getting started docs

---

src/content/tutorials/drizzle-with-db/drizzle-with-turso.mdx

fix typo in drizzle-with-turso tutorial

---

src/content/tutorials/drizzle-with-db/drizzle-with-supabase.mdx

fix: typo in drizzle-with-supabase.mdx

---

src/content/tutorials/drizzle-with-frameworks/drizzle-nextjs-neon.mdx

Update Todo app tutorial
cc: #342

update todo app tutorial

---

src/content/documentation/docs/overview.mdx

There are a lot of small mistakes throughout the docs. I'm happy to correct more pages if there's interest.

Corrections to overview

---

src/data/roadmap.md

 Fixes typo in roadmap.md

---

src/content/documentation/docs/set-operations.mdx

Just a quick capitalization fix I saw when reading through the docs.

Fix: Capitalization in set-operations.mdx

---

src/content/documentation/docs/column-types/pg.mdx

docs(column-types): update pg.mdx

---

src/content/documentation/docs/rqb.mdx

Ran into this today and found the solution in an old AnswerOverflow forum post.
https://www.answeroverflow.com/m/1173301063642787880
Figure it should be in the docs.

docs: Added foreign key action callback syntax example

---

src/components/markdown/get-started/mysql/ConnectTiDB.mdx
src/components/markdown/get-started/postgresql/ConnectNeon.mdx
src/components/markdown/get-started/postgresql/ConnectPgLite.mdx
src/components/markdown/get-started/postgresql/ConnectPostgreSQL.mdx
src/components/markdown/get-started/postgresql/ConnectVercel.mdx
src/components/markdown/get-started/sqlite/ConnectBun.mdx
src/components/markdown/get-started/sqlite/ConnectLibsql.mdx
src/content/documentation/docs/connect-aws-data-api-pg.mdx
src/content/documentation/docs/connect-bun-sqlite.mdx
src/content/documentation/docs/connect-neon.mdx
src/content/documentation/docs/connect-pglite.mdx
src/content/documentation/docs/connect-tidb.mdx
src/content/documentation/docs/connect-turso.mdx
src/content/documentation/docs/connect-vercel-postgres.mdx
src/content/documentation/docs/get-started-postgresql.mdx
src/content/documentation/docs/get-started-sqlite.mdx
src/content/documentation/docs/get-started/turso-existing.mdx
src/content/documentation/docs/get-started/turso-new.mdx

Was trying to upgrade and noticed the docs still have the old import for the monodriver
Not sure if I found them all...

docs: update monodriver import

---

src/content/documentation/docs/drizzle-kit-up.mdx

typo fix: our -> out

---

src/content/documentation/docs/connect-bun-sqlite.mdx

fixes a typo in the import line of the bun sqlite driver in its connection guide

fix import typo in bun sqlite

---

src/content/documentation/docs/column-types/mysql.mdx
src/content/documentation/docs/column-types/pg.mdx
src/content/documentation/docs/column-types/sqlite.mdx

Fix for https://github.com/drizzle-team/drizzle-orm/issues/3107.

docs(column-types): fix broken sql schema declaration links

---

src/data/aside-sponsors.ts

Fixed to reduce flickering when hovering the logo.
Before
https://github.com/user-attachments/assets/b1ae2230-e417-4e61-8116-c365a50d10e6
After
https://github.com/user-attachments/assets/1b3580f4-debd-426b-8865-48cb6aaa9062

Reduces flickering on hover

---

src/content/docs/zod.mdx

This PR complements https://github.com/drizzle-team/drizzle-orm/pull/3852.

`drizzle-zod` type coercion docs

---

src/content/docs/drizzle-kit-studio.mdx

was looking into the docs for drizzle studio to see if it was open source b/c i want to build something with a similar paradigm to it, sad its not but thought i'd fix a few typos while i was here :)

Typos in Drizzle Studio Page

---

src/content/docs/connect-drizzle-proxy.mdx

- Mixed use of tabs and spaces causing the indentation issue, makes the code hard to read and understand.
- Unified with spaces as it's more common across the documentation.
- Some code has incorrect tabs to indent, corrected already.

docs: mixed use of tabs and spaces causing indent issues

---

src/content/docs/_meta.json
src/content/docs/arktype.mdx
src/content/docs/typebox.mdx
src/content/docs/valibot.mdx
src/content/docs/zod.mdx

This PR updates the docs according to https://github.com/drizzle-team/drizzle-orm/pull/4097 and https://github.com/drizzle-team/drizzle-orm/pull/4314.

Arktype docs + some other updates

---

pnpm-lock.yaml
src/content/docs/_meta.json
src/content/docs/connect-prisma-postgres.mdx

Hey Drizzle team 🙌 
I added a page for Prisma Postgres to the docs showing how to connect via node-postgres and postgres.js, how does that look to you? 
I imitated the structure of the other pages in that section and also added a note about our [serverless driver](https://www.prisma.io/docs/postgres/database/serverless-driver) which hopefully can be supported by Drizzle in the future as well 🙏 
Let me know if you want me to adjust anything, we're looking forward to see this live 😄

add prisma postgres page

---

src/content/docs/tutorials/drizzle-with-db/drizzle-with-turso.mdx

Fix minor typo on field name.
> https://github.com/drizzle-team/drizzle-orm/pull/4444
Also created a PR for `examples`
- https://github.com/drizzle-team/drizzle-orm/pull/4444

docs(turso): fix field name typo

---

src/content/docs/drizzle-kit-studio.mdx

Updates config to accommodate changes made in v0.21.0.

fix(drizzle-kit-studio.mdx): add dialect to config

---

src/data/shipping.yaml

This pull request includes a small change to the `src/data/shipping.yaml` file. The change corrects a typo by replacing "Sytnax" with "Syntax" in the text.

Fixed typo
